name: DEPLOYMENT

on:
  workflow_dispatch:
    inputs:
      start_environment:
        description: 'Choose deployment environment...'
        required: true
        type: choice
        options:
        - development
        - testing
        - staging
        - production

env:
  ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
  NAMESPACE: ${{ secrets.NAMESPACE }}
  CI_WORKFLOW_NAME: "BUILD"

jobs:
  fetch_latest_build:
    runs-on: ubuntu-latest
    outputs:
      docker_tag: ${{ steps.get_build_info.outputs.docker_tag }}
    steps:
    - name: Get latest successful Build ID
      id: get_build_run
      uses: actions/github-script@v7
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
            const workflow_name = process.env.CI_WORKFLOW_NAME;
            const { data: runs } = await github.rest.actions.listWorkflowRuns({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: workflow_name,
                status: 'success',
                branch: 'feature/*',
                per_page: 1
            });
            core.setOutput('run_id', runs.workflow_runs[0].id);

    - name: Obtain build information
      id: get_build_info
      run: |
        DOCKER_TAG=$(cat build_info.txt)
        echo "docker_tag=${DOCKER_TAG}" >> $GITHUB_OUTPUT